### ISSUE TITLE
webui更新后出了点问题

### ISSUE THREAD

**Issue by Yidhar** [7eu7d7/ML-Danbooru-webui#3]
Error loading script: mld_main.py
Traceback (most recent call last):
  File "D:\sd\stable-diffusion-webui\modules\scripts.py", line 257, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "D:\sd\stable-diffusion-webui\modules\script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\sd\stable-diffusion-webui\extensions\ML-Danbooru-webui\scripts\mld_main.py", line 3, in <module>
    from mldanbooru.interface import Infer
  File "D:\sd\stable-diffusion-webui\extensions\ML-Danbooru-webui\mldanbooru\__init__.py", line 1, in <module>
    from .utils import create_model
  File "D:\sd\stable-diffusion-webui\extensions\ML-Danbooru-webui\mldanbooru\utils\__init__.py", line 1, in <module>
    from .factory import create_model
  File "D:\sd\stable-diffusion-webui\extensions\ML-Danbooru-webui\mldanbooru\utils\factory.py", line 3, in <module>
    from ..caformer import build_caformer
  File "D:\sd\stable-diffusion-webui\extensions\ML-Danbooru-webui\mldanbooru\caformer\__init__.py", line 1, in <module>
    from .ml_caformer import build_caformer
  File "D:\sd\stable-diffusion-webui\extensions\ML-Danbooru-webui\mldanbooru\caformer\ml_caformer.py", line 8, in <module>
    from .metaformer_baselines import MetaFormer
  File "D:\sd\stable-diffusion-webui\extensions\ML-Danbooru-webui\mldanbooru\caformer\metaformer_baselines.py", line 28, in <module>
    from einops import rearrange, einsum
ImportError: cannot import name 'einsum' from 'einops' (D:\sd\stable-diffusion-webui\venv\lib\site-packages\einops\__init__.py)

**Comment by IrisRainbowNeko** [comment]
einops版本太旧了，现在强制卸载重装，更新下试试

**Comment by jackw111** [comment]
![image](https://github.com/7eu7d7/ML-Danbooru-webui/assets/127837373/e440e6c6-f187-4f6c-8aa1-6e008bbcc1a0)
跟上面的朋友问题一样
更新后还是会报错
